version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: triarb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  app:
    build: .
    command: ["bash", "-lc", "make run"]
    env_file:
      - .env
    depends_on:
      - redis
      - db
    ports:
      - "8081:8081"
      - "9000:9000"
